image: docker:stable

variables:
   # When using dind, it's wise to use the overlayfs driver for
   # improved performance.
   DOCKER_DRIVER: overlay2

   # GCP Container Registry domain
   GCP_CR_DOMAIN: eu.gcr.io


services:
  - docker:dind

before_script:
  # Env vars
     # Docker base image tag
  - export DOCKER_IMAGE_BASE_TAG="${GCP_CR_DOMAIN}/audiadis-infrastructure"
  - docker info

  # Installing docker-compose
  - apk add --no-cache py-pip
  - pip install docker-compose

  # Docker login for the GCP Container regustry
  - echo "$GCP_SERVICE_ACCOUNT_KEY" > key.json
  - docker login -u _json_key --password-stdin "https://${GCP_CR_DOMAIN}" < key.json

stages:
  - build
  - test


build:
  stage: build
  script:
    - docker-compose build
    - docker tag webapi "${DOCKER_IMAGE_BASE_TAG}/webapi:${CI_COMMIT_SHA}"
    - docker push "${DOCKER_IMAGE_BASE_TAG}/webapi:${CI_COMMIT_SHA}"

test:
  stage: test
  script:
    - docker pull "${DOCKER_IMAGE_BASE_TAG}/webapi:${CI_COMMIT_SHA}"
    - docker tag "${DOCKER_IMAGE_BASE_TAG}/webapi:${CI_COMMIT_SHA}" webapi
    - docker-compose run --rm webapi sh -c 'pytest --cov'
