# Docker compose for local/dev environment
version: "3"

services:
  webapi:
    build:
      context: .
    image: webapi
    environment:
      - REDIS_HOSTNAME=redis
    volumes:
      - ./:/code/
    ports:
      - "80:5000"
    networks:
      - api_network
    depends_on:
      - redis

  redis:
    image: "redis:5.0.2-alpine"
    networks:
      - api_network

networks:
  api_network:
