# Docker compose for local/dev environment
version: "3.7"

services:
  webapi:
    build:
      context: .
      target: release
    image: webapi
    environment:
      - REDIS_HOSTNAME=redis
    volumes:
      - ./:/code/
    ports:
      - "80:5000"
    networks:
      - api_network
    depends_on:
      - redis

  redis:
    image: "redis:5.0.2-alpine"
    ports:
      - "6379:6379"
    networks:
      - api_network

networks:
  api_network:
